jobs:
  publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      run: echo "Will start a Maven Central upload with version ${{ github.event.inputs.releaseversion
        }}"
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Maven Central Repository
      uses: actions/setup-java@v4
      with:
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        java-version: 8
        server-id: sonatype-nexus-staging
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Set projects Maven version to GitHub Action GUI set version
      run: mvn versions:set "-DnewVersion=${{ github.event.inputs.releaseversion }}"
    - continue-on-error: true
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
        MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
      name: Publish package
      run: mvn --batch-mode clean deploy -P central-deploy -DskipTests=true
name: Release to maven central
on:
  repository_dispatch:
    types: trigger-ga___release-to-maven-central.yml
